# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.5

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/multikinect-linux/git/integrated_project

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/multikinect-linux/git/integrated_project

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/multikinect-linux/git/integrated_project/CMakeFiles /home/multikinect-linux/git/integrated_project/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/multikinect-linux/git/integrated_project/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named CalibrationPratice

# Build rule for target.
CalibrationPratice: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 CalibrationPratice
.PHONY : CalibrationPratice

# fast build rule for target.
CalibrationPratice/fast:
	$(MAKE) -f CMakeFiles/CalibrationPratice.dir/build.make CMakeFiles/CalibrationPratice.dir/build
.PHONY : CalibrationPratice/fast

#=============================================================================
# Target rules for targets named Protonect

# Build rule for target.
Protonect: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 Protonect
.PHONY : Protonect

# fast build rule for target.
Protonect/fast:
	$(MAKE) -f CMakeFiles/Protonect.dir/build.make CMakeFiles/Protonect.dir/build
.PHONY : Protonect/fast

#=============================================================================
# Target rules for targets named NiViewerTest

# Build rule for target.
NiViewerTest: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 NiViewerTest
.PHONY : NiViewerTest

# fast build rule for target.
NiViewerTest/fast:
	$(MAKE) -f CMakeFiles/NiViewerTest.dir/build.make CMakeFiles/NiViewerTest.dir/build
.PHONY : NiViewerTest/fast

#=============================================================================
# Target rules for targets named TrackingTest

# Build rule for target.
TrackingTest: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 TrackingTest
.PHONY : TrackingTest

# fast build rule for target.
TrackingTest/fast:
	$(MAKE) -f CMakeFiles/TrackingTest.dir/build.make CMakeFiles/TrackingTest.dir/build
.PHONY : TrackingTest/fast

#=============================================================================
# Target rules for targets named ClassifyTest

# Build rule for target.
ClassifyTest: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ClassifyTest
.PHONY : ClassifyTest

# fast build rule for target.
ClassifyTest/fast:
	$(MAKE) -f CMakeFiles/ClassifyTest.dir/build.make CMakeFiles/ClassifyTest.dir/build
.PHONY : ClassifyTest/fast

src/Common/flextGL.o: src/Common/flextGL.cpp.o

.PHONY : src/Common/flextGL.o

# target to build an object file
src/Common/flextGL.cpp.o:
	$(MAKE) -f CMakeFiles/Protonect.dir/build.make CMakeFiles/Protonect.dir/src/Common/flextGL.cpp.o
	$(MAKE) -f CMakeFiles/ClassifyTest.dir/build.make CMakeFiles/ClassifyTest.dir/src/Common/flextGL.cpp.o
.PHONY : src/Common/flextGL.cpp.o

src/Common/flextGL.i: src/Common/flextGL.cpp.i

.PHONY : src/Common/flextGL.i

# target to preprocess a source file
src/Common/flextGL.cpp.i:
	$(MAKE) -f CMakeFiles/Protonect.dir/build.make CMakeFiles/Protonect.dir/src/Common/flextGL.cpp.i
	$(MAKE) -f CMakeFiles/ClassifyTest.dir/build.make CMakeFiles/ClassifyTest.dir/src/Common/flextGL.cpp.i
.PHONY : src/Common/flextGL.cpp.i

src/Common/flextGL.s: src/Common/flextGL.cpp.s

.PHONY : src/Common/flextGL.s

# target to generate assembly for a file
src/Common/flextGL.cpp.s:
	$(MAKE) -f CMakeFiles/Protonect.dir/build.make CMakeFiles/Protonect.dir/src/Common/flextGL.cpp.s
	$(MAKE) -f CMakeFiles/ClassifyTest.dir/build.make CMakeFiles/ClassifyTest.dir/src/Common/flextGL.cpp.s
.PHONY : src/Common/flextGL.cpp.s

src/Common/viewer.o: src/Common/viewer.cpp.o

.PHONY : src/Common/viewer.o

# target to build an object file
src/Common/viewer.cpp.o:
	$(MAKE) -f CMakeFiles/Protonect.dir/build.make CMakeFiles/Protonect.dir/src/Common/viewer.cpp.o
	$(MAKE) -f CMakeFiles/ClassifyTest.dir/build.make CMakeFiles/ClassifyTest.dir/src/Common/viewer.cpp.o
.PHONY : src/Common/viewer.cpp.o

src/Common/viewer.i: src/Common/viewer.cpp.i

.PHONY : src/Common/viewer.i

# target to preprocess a source file
src/Common/viewer.cpp.i:
	$(MAKE) -f CMakeFiles/Protonect.dir/build.make CMakeFiles/Protonect.dir/src/Common/viewer.cpp.i
	$(MAKE) -f CMakeFiles/ClassifyTest.dir/build.make CMakeFiles/ClassifyTest.dir/src/Common/viewer.cpp.i
.PHONY : src/Common/viewer.cpp.i

src/Common/viewer.s: src/Common/viewer.cpp.s

.PHONY : src/Common/viewer.s

# target to generate assembly for a file
src/Common/viewer.cpp.s:
	$(MAKE) -f CMakeFiles/Protonect.dir/build.make CMakeFiles/Protonect.dir/src/Common/viewer.cpp.s
	$(MAKE) -f CMakeFiles/ClassifyTest.dir/build.make CMakeFiles/ClassifyTest.dir/src/Common/viewer.cpp.s
.PHONY : src/Common/viewer.cpp.s

src/OpenCVPractice/stereo_calib.o: src/OpenCVPractice/stereo_calib.cpp.o

.PHONY : src/OpenCVPractice/stereo_calib.o

# target to build an object file
src/OpenCVPractice/stereo_calib.cpp.o:
	$(MAKE) -f CMakeFiles/CalibrationPratice.dir/build.make CMakeFiles/CalibrationPratice.dir/src/OpenCVPractice/stereo_calib.cpp.o
.PHONY : src/OpenCVPractice/stereo_calib.cpp.o

src/OpenCVPractice/stereo_calib.i: src/OpenCVPractice/stereo_calib.cpp.i

.PHONY : src/OpenCVPractice/stereo_calib.i

# target to preprocess a source file
src/OpenCVPractice/stereo_calib.cpp.i:
	$(MAKE) -f CMakeFiles/CalibrationPratice.dir/build.make CMakeFiles/CalibrationPratice.dir/src/OpenCVPractice/stereo_calib.cpp.i
.PHONY : src/OpenCVPractice/stereo_calib.cpp.i

src/OpenCVPractice/stereo_calib.s: src/OpenCVPractice/stereo_calib.cpp.s

.PHONY : src/OpenCVPractice/stereo_calib.s

# target to generate assembly for a file
src/OpenCVPractice/stereo_calib.cpp.s:
	$(MAKE) -f CMakeFiles/CalibrationPratice.dir/build.make CMakeFiles/CalibrationPratice.dir/src/OpenCVPractice/stereo_calib.cpp.s
.PHONY : src/OpenCVPractice/stereo_calib.cpp.s

src/OpenNiTest/UserTrackingTest.o: src/OpenNiTest/UserTrackingTest.cpp.o

.PHONY : src/OpenNiTest/UserTrackingTest.o

# target to build an object file
src/OpenNiTest/UserTrackingTest.cpp.o:
	$(MAKE) -f CMakeFiles/TrackingTest.dir/build.make CMakeFiles/TrackingTest.dir/src/OpenNiTest/UserTrackingTest.cpp.o
.PHONY : src/OpenNiTest/UserTrackingTest.cpp.o

src/OpenNiTest/UserTrackingTest.i: src/OpenNiTest/UserTrackingTest.cpp.i

.PHONY : src/OpenNiTest/UserTrackingTest.i

# target to preprocess a source file
src/OpenNiTest/UserTrackingTest.cpp.i:
	$(MAKE) -f CMakeFiles/TrackingTest.dir/build.make CMakeFiles/TrackingTest.dir/src/OpenNiTest/UserTrackingTest.cpp.i
.PHONY : src/OpenNiTest/UserTrackingTest.cpp.i

src/OpenNiTest/UserTrackingTest.s: src/OpenNiTest/UserTrackingTest.cpp.s

.PHONY : src/OpenNiTest/UserTrackingTest.s

# target to generate assembly for a file
src/OpenNiTest/UserTrackingTest.cpp.s:
	$(MAKE) -f CMakeFiles/TrackingTest.dir/build.make CMakeFiles/TrackingTest.dir/src/OpenNiTest/UserTrackingTest.cpp.s
.PHONY : src/OpenNiTest/UserTrackingTest.cpp.s

src/OpenNiTest/niViewerTest.o: src/OpenNiTest/niViewerTest.cpp.o

.PHONY : src/OpenNiTest/niViewerTest.o

# target to build an object file
src/OpenNiTest/niViewerTest.cpp.o:
	$(MAKE) -f CMakeFiles/NiViewerTest.dir/build.make CMakeFiles/NiViewerTest.dir/src/OpenNiTest/niViewerTest.cpp.o
.PHONY : src/OpenNiTest/niViewerTest.cpp.o

src/OpenNiTest/niViewerTest.i: src/OpenNiTest/niViewerTest.cpp.i

.PHONY : src/OpenNiTest/niViewerTest.i

# target to preprocess a source file
src/OpenNiTest/niViewerTest.cpp.i:
	$(MAKE) -f CMakeFiles/NiViewerTest.dir/build.make CMakeFiles/NiViewerTest.dir/src/OpenNiTest/niViewerTest.cpp.i
.PHONY : src/OpenNiTest/niViewerTest.cpp.i

src/OpenNiTest/niViewerTest.s: src/OpenNiTest/niViewerTest.cpp.s

.PHONY : src/OpenNiTest/niViewerTest.s

# target to generate assembly for a file
src/OpenNiTest/niViewerTest.cpp.s:
	$(MAKE) -f CMakeFiles/NiViewerTest.dir/build.make CMakeFiles/NiViewerTest.dir/src/OpenNiTest/niViewerTest.cpp.s
.PHONY : src/OpenNiTest/niViewerTest.cpp.s

src/Protonect/Protonect.o: src/Protonect/Protonect.cpp.o

.PHONY : src/Protonect/Protonect.o

# target to build an object file
src/Protonect/Protonect.cpp.o:
	$(MAKE) -f CMakeFiles/Protonect.dir/build.make CMakeFiles/Protonect.dir/src/Protonect/Protonect.cpp.o
.PHONY : src/Protonect/Protonect.cpp.o

src/Protonect/Protonect.i: src/Protonect/Protonect.cpp.i

.PHONY : src/Protonect/Protonect.i

# target to preprocess a source file
src/Protonect/Protonect.cpp.i:
	$(MAKE) -f CMakeFiles/Protonect.dir/build.make CMakeFiles/Protonect.dir/src/Protonect/Protonect.cpp.i
.PHONY : src/Protonect/Protonect.cpp.i

src/Protonect/Protonect.s: src/Protonect/Protonect.cpp.s

.PHONY : src/Protonect/Protonect.s

# target to generate assembly for a file
src/Protonect/Protonect.cpp.s:
	$(MAKE) -f CMakeFiles/Protonect.dir/build.make CMakeFiles/Protonect.dir/src/Protonect/Protonect.cpp.s
.PHONY : src/Protonect/Protonect.cpp.s

src/SimpleFreenect/main.o: src/SimpleFreenect/main.cpp.o

.PHONY : src/SimpleFreenect/main.o

# target to build an object file
src/SimpleFreenect/main.cpp.o:
	$(MAKE) -f CMakeFiles/ClassifyTest.dir/build.make CMakeFiles/ClassifyTest.dir/src/SimpleFreenect/main.cpp.o
.PHONY : src/SimpleFreenect/main.cpp.o

src/SimpleFreenect/main.i: src/SimpleFreenect/main.cpp.i

.PHONY : src/SimpleFreenect/main.i

# target to preprocess a source file
src/SimpleFreenect/main.cpp.i:
	$(MAKE) -f CMakeFiles/ClassifyTest.dir/build.make CMakeFiles/ClassifyTest.dir/src/SimpleFreenect/main.cpp.i
.PHONY : src/SimpleFreenect/main.cpp.i

src/SimpleFreenect/main.s: src/SimpleFreenect/main.cpp.s

.PHONY : src/SimpleFreenect/main.s

# target to generate assembly for a file
src/SimpleFreenect/main.cpp.s:
	$(MAKE) -f CMakeFiles/ClassifyTest.dir/build.make CMakeFiles/ClassifyTest.dir/src/SimpleFreenect/main.cpp.s
.PHONY : src/SimpleFreenect/main.cpp.s

src/SimpleFreenect/simpleprotonect.o: src/SimpleFreenect/simpleprotonect.cpp.o

.PHONY : src/SimpleFreenect/simpleprotonect.o

# target to build an object file
src/SimpleFreenect/simpleprotonect.cpp.o:
	$(MAKE) -f CMakeFiles/ClassifyTest.dir/build.make CMakeFiles/ClassifyTest.dir/src/SimpleFreenect/simpleprotonect.cpp.o
.PHONY : src/SimpleFreenect/simpleprotonect.cpp.o

src/SimpleFreenect/simpleprotonect.i: src/SimpleFreenect/simpleprotonect.cpp.i

.PHONY : src/SimpleFreenect/simpleprotonect.i

# target to preprocess a source file
src/SimpleFreenect/simpleprotonect.cpp.i:
	$(MAKE) -f CMakeFiles/ClassifyTest.dir/build.make CMakeFiles/ClassifyTest.dir/src/SimpleFreenect/simpleprotonect.cpp.i
.PHONY : src/SimpleFreenect/simpleprotonect.cpp.i

src/SimpleFreenect/simpleprotonect.s: src/SimpleFreenect/simpleprotonect.cpp.s

.PHONY : src/SimpleFreenect/simpleprotonect.s

# target to generate assembly for a file
src/SimpleFreenect/simpleprotonect.cpp.s:
	$(MAKE) -f CMakeFiles/ClassifyTest.dir/build.make CMakeFiles/ClassifyTest.dir/src/SimpleFreenect/simpleprotonect.cpp.s
.PHONY : src/SimpleFreenect/simpleprotonect.cpp.s

src/SimpleFreenect/simpletracker.o: src/SimpleFreenect/simpletracker.cpp.o

.PHONY : src/SimpleFreenect/simpletracker.o

# target to build an object file
src/SimpleFreenect/simpletracker.cpp.o:
	$(MAKE) -f CMakeFiles/ClassifyTest.dir/build.make CMakeFiles/ClassifyTest.dir/src/SimpleFreenect/simpletracker.cpp.o
.PHONY : src/SimpleFreenect/simpletracker.cpp.o

src/SimpleFreenect/simpletracker.i: src/SimpleFreenect/simpletracker.cpp.i

.PHONY : src/SimpleFreenect/simpletracker.i

# target to preprocess a source file
src/SimpleFreenect/simpletracker.cpp.i:
	$(MAKE) -f CMakeFiles/ClassifyTest.dir/build.make CMakeFiles/ClassifyTest.dir/src/SimpleFreenect/simpletracker.cpp.i
.PHONY : src/SimpleFreenect/simpletracker.cpp.i

src/SimpleFreenect/simpletracker.s: src/SimpleFreenect/simpletracker.cpp.s

.PHONY : src/SimpleFreenect/simpletracker.s

# target to generate assembly for a file
src/SimpleFreenect/simpletracker.cpp.s:
	$(MAKE) -f CMakeFiles/ClassifyTest.dir/build.make CMakeFiles/ClassifyTest.dir/src/SimpleFreenect/simpletracker.cpp.s
.PHONY : src/SimpleFreenect/simpletracker.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... CalibrationPratice"
	@echo "... Protonect"
	@echo "... NiViewerTest"
	@echo "... TrackingTest"
	@echo "... ClassifyTest"
	@echo "... src/Common/flextGL.o"
	@echo "... src/Common/flextGL.i"
	@echo "... src/Common/flextGL.s"
	@echo "... src/Common/viewer.o"
	@echo "... src/Common/viewer.i"
	@echo "... src/Common/viewer.s"
	@echo "... src/OpenCVPractice/stereo_calib.o"
	@echo "... src/OpenCVPractice/stereo_calib.i"
	@echo "... src/OpenCVPractice/stereo_calib.s"
	@echo "... src/OpenNiTest/UserTrackingTest.o"
	@echo "... src/OpenNiTest/UserTrackingTest.i"
	@echo "... src/OpenNiTest/UserTrackingTest.s"
	@echo "... src/OpenNiTest/niViewerTest.o"
	@echo "... src/OpenNiTest/niViewerTest.i"
	@echo "... src/OpenNiTest/niViewerTest.s"
	@echo "... src/Protonect/Protonect.o"
	@echo "... src/Protonect/Protonect.i"
	@echo "... src/Protonect/Protonect.s"
	@echo "... src/SimpleFreenect/main.o"
	@echo "... src/SimpleFreenect/main.i"
	@echo "... src/SimpleFreenect/main.s"
	@echo "... src/SimpleFreenect/simpleprotonect.o"
	@echo "... src/SimpleFreenect/simpleprotonect.i"
	@echo "... src/SimpleFreenect/simpleprotonect.s"
	@echo "... src/SimpleFreenect/simpletracker.o"
	@echo "... src/SimpleFreenect/simpletracker.i"
	@echo "... src/SimpleFreenect/simpletracker.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

